#!/bin/bash
set -e

export TORCH_URL=https://github.com/ultralytics/assets/releases/download/v0.0.0
export TORCH_PACKAGE=torch-2.5.0-cp310-cp310-linux_aarch64.whl
export TORCHVISION_URL=https://github.com/ultralytics/assets/releases/download/v0.0.0
export TORCHVISION_PACKAGE=torchvision-0.20.0a0+afc54f7-cp310-cp310-linux_aarch64.whl

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then
    echo "Object Tracker: Installing Nvidia Python dependencies"
    if ! pip3 list 2>/dev/null | grep -q "^torch "; then
        wget $TORCH_URL/$TORCH_PACKAGE -O /tmp/$TORCH_PACKAGE
        pip3 install /tmp/$TORCH_PACKAGE
    fi
    if ! pip3 list 2>/dev/null | grep -q "^torchvision "; then
        wget $TORCHVISION_URL/$TORCHVISION_PACKAGE -O /tmp/$TORCHVISION_PACKAGE
        pip3 install /tmp/$TORCHVISION_PACKAGE
    fi
    rm -f /tmp/*.whl

    echo "Object Tracker: Installing Python dependencies"
    pip3 install --upgrade pip
    pip3 install git+https://github.com/starwit/vision-api.git@3.2.0#subdirectory=python/visionapi
    pip3 install git+https://github.com/starwit/vision-lib.git@0.11.2#subdirectory=python

    pip3 install boxmot filterpy

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/objecttracker <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/objecttracker

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/objecttracker    

    # link settings file from etc
    cd /opt/starwit/objecttracker
    ln -s /etc/starwit/objecttracker/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start objecttracker.service        
    systemctl enable objecttracker.service
fi

#DEBHELPER#

exit 0