#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then
    python -m pip install --user virtualenv
    export PATH=/root/.local/bin:$PATH
    echo "Create virtual environment for application"
    cd "/opt/starwit/objecttracker"
    virtualenv --system-site-packages .venv
    source .venv/bin/activate

    pip3 install boxmot==13.0.8 --no-deps

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/objecttracker <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/objecttracker

source .venv/bin/activate

python main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/objecttracker    

    # link settings file from etc
    cd /opt/starwit/objecttracker
    ln -s /etc/starwit/objecttracker/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start objecttracker.service        
    systemctl enable objecttracker.service
fi

#DEBHELPER#

exit 0