name: Build and release latest APT package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: package APT
    runs-on: [self-hosted, linux, X64]
    container:
        image: starwitorg/debian-packaging:0.0.2
        env:
          PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD_FLAT }}
          GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY_B64 }}          
        volumes:
            - ./:/code

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build package
        run: |
            export PATH=/root/.local/bin/:$PATH
            bash -c ./start_make.sh
            echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
            echo "Done building APT package"
      - name: create release
        run: |
          cd /code
          echo "Releasing package with version ${VERSION}"
          gh release create ${VERSION} --title "${VERSION}" ./target/*deb ./target/*.dsc
        env:
          GH_TOKEN: ${{ github.token }}